### ISSUE TITLE
Intervals Closed/Open backwards??

### ISSUE THREAD

**Issue by g-as** [antonagestam/phantom-types#231]
Hi,

reading the docs and [the code](https://github.com/antonagestam/phantom-types/blob/main/src/phantom/predicates/interval.py), I feel there's an inversion.

```python
def open(low: T, high: T) -> Predicate[SupportsLeGe[T]]:
    """
    Create a predicate that succeeds when its argument is in the range ``(low, high)``.
    """

    @bind_name(open, low, high)
    def check(value: SupportsLeGe[T]) -> bool:
        return low <= value <= high

    return check
```
Here I would have expected `return low < value < high`

https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology

In an open interval, bounds are not included, while in a closed one, they are.

Am I missing something? Am I reading the code wrong?

**Comment by antonagestam** [comment]
Oh my, this is embarrassing. This is an oversight and should be fixed.

**Comment by g-as** [comment]
Hahaha, no worries.

Let me know if I can help. Either draft a PR or review one if you want to do it yourself.

**Comment by antonagestam** [comment]
@g-as Feel free to open a PR, I might not be able to act on this immediately but will probably get to it in a few weeks at the latest otherwise. I think the change should just be a matter of renaming things in implementation, tests and docs.

This of course is breaking backwards incompatibility in a very harsh way. Fortunately I don't have any other outstanding issues that I feel is needs addressing before releasing 1.0. Perhaps it'd be a good idea to issue an intermediary release before the fix, that triggers warnings for all usages of open/closed just saying that they will be renamed in 1.0. Please let me know if you have ideas, and a big thank you for raising this awkward issue 😅

**Comment by g-as** [comment]
An intermediate release definitely feels necessary.

Warnings should do the trick as long as a there's a decent amount of time between the intermediary release and the eventual 1.0.

A way to speed up the process could be to rename `phantom/interval.py` and `phantom/predicates/interval.py`.

Examples:
- `phantom/interval.py` -> `phantom/interval_deprecated.py` in 0.19 (raising a custom import error when importing `phantom/interval.py`) and `phantom/interval_deprecated.py` -> `phantom/interval.py` in 1.0 (with the fixes)
- `phantom/interval.py` raising warnings in 0.19, `phantom/interval.py` -> `phantom/interval_fixed.py` in 1.0 (with the fixes), and `phantom/interval_fixed.py` -> `phantom/interval.py` in 2.0

But it is costly for both lib and user side.

Another option could be to introduce an immediately deprecated flag in 0.19 that is set with an env or global var. In 0.19, it could have a default value (old behaviour). In 0.20 it must be defined (to old or new behaviour). In 1.0, flag and old behaviour are removed.
